config:
  send_anonymous_usage_stats: False
  use_colors: True
  partial_parse: True

airbyte_lab:
  outputs:
    dev:
      type: clickhouse
      schema: default
      host: rc1b-vi8fj93aamh2690k.mdb.yandexcloud.net
      port: 8443
      user: admin
      password: yivanovskaya
      secure: True
      verify: False
    ci:
      type: clickhouse
      host: clickhouse
      port: 8123
      schema: default
      threads: 4
  target: dev
